title: Rscoop
description: A desktop GUI for the Scoop package manager
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
color_scheme: dark
search_enabled: true
logo: assets/images/logo.png
favicon_ico: assets/images/favicon.ico
aux_links:
  "GitHub": https://github.com/AmarBego/rscoop
nav_external_links:
  - title: Download
    url: https://github.com/AmarBego/Rscoop/releases/latest
    hide_icon: false
footer_content: "Copyright &copy; 2025-2026 AmarBego. Built with Rust, SolidJS, and Tauri."
